# Generated by Django 4.2.6 on 2023-11-06 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classschedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldata',
            old_name='topic',
            new_name='name',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classschedule.personaldata'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='classroom_number',
            field=models.IntegerField(default=2),
        ),
    ]
